// Copyright (c) 2017, The Regents of the University of California.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// * Neither the names of the copyright holders nor the names of their
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.19.2
// source: protobuf/upf_ebpf_msg.proto

package bess_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeysData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcIface      uint64 `protobuf:"varint,1,opt,name=srcIface,proto3" json:"srcIface,omitempty"`
	TunnelIP4Dst  uint32 `protobuf:"varint,2,opt,name=tunnelIP4Dst,proto3" json:"tunnelIP4Dst,omitempty"`
	TunnelTEID    uint32 `protobuf:"varint,3,opt,name=tunnelTEID,proto3" json:"tunnelTEID,omitempty"`
	UeIPsrcAddr   uint32 `protobuf:"varint,4,opt,name=ueIPsrcAddr,proto3" json:"ueIPsrcAddr,omitempty"`
	InetIPdstAddr uint32 `protobuf:"varint,5,opt,name=inetIPdstAddr,proto3" json:"inetIPdstAddr,omitempty"`
	UeSrcPort     uint32 `protobuf:"varint,6,opt,name=ueSrcPort,proto3" json:"ueSrcPort,omitempty"`
	InetSrcPort   uint32 `protobuf:"varint,7,opt,name=inetSrcPort,proto3" json:"inetSrcPort,omitempty"`
	ProtoID       uint32 `protobuf:"varint,8,opt,name=protoID,proto3" json:"protoID,omitempty"`
}

func (x *KeysData) Reset() {
	*x = KeysData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeysData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysData) ProtoMessage() {}

func (x *KeysData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysData.ProtoReflect.Descriptor instead.
func (*KeysData) Descriptor() ([]byte, []int) {
	return file_protobuf_upf_ebpf_msg_proto_rawDescGZIP(), []int{0}
}

func (x *KeysData) GetSrcIface() uint64 {
	if x != nil {
		return x.SrcIface
	}
	return 0
}

func (x *KeysData) GetTunnelIP4Dst() uint32 {
	if x != nil {
		return x.TunnelIP4Dst
	}
	return 0
}

func (x *KeysData) GetTunnelTEID() uint32 {
	if x != nil {
		return x.TunnelTEID
	}
	return 0
}

func (x *KeysData) GetUeIPsrcAddr() uint32 {
	if x != nil {
		return x.UeIPsrcAddr
	}
	return 0
}

func (x *KeysData) GetInetIPdstAddr() uint32 {
	if x != nil {
		return x.InetIPdstAddr
	}
	return 0
}

func (x *KeysData) GetUeSrcPort() uint32 {
	if x != nil {
		return x.UeSrcPort
	}
	return 0
}

func (x *KeysData) GetInetSrcPort() uint32 {
	if x != nil {
		return x.InetSrcPort
	}
	return 0
}

func (x *KeysData) GetProtoID() uint32 {
	if x != nil {
		return x.ProtoID
	}
	return 0
}

type ValuesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdrID uint64 `protobuf:"varint,1,opt,name=pdrID,proto3" json:"pdrID,omitempty"`
	FseID uint32 `protobuf:"varint,2,opt,name=fseID,proto3" json:"fseID,omitempty"`
	CtrID uint32 `protobuf:"varint,3,opt,name=ctrID,proto3" json:"ctrID,omitempty"`
	QerID uint32 `protobuf:"varint,4,opt,name=qerID,proto3" json:"qerID,omitempty"`
	FarID uint32 `protobuf:"varint,5,opt,name=farID,proto3" json:"farID,omitempty"`
}

func (x *ValuesData) Reset() {
	*x = ValuesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValuesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesData) ProtoMessage() {}

func (x *ValuesData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesData.ProtoReflect.Descriptor instead.
func (*ValuesData) Descriptor() ([]byte, []int) {
	return file_protobuf_upf_ebpf_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ValuesData) GetPdrID() uint64 {
	if x != nil {
		return x.PdrID
	}
	return 0
}

func (x *ValuesData) GetFseID() uint32 {
	if x != nil {
		return x.FseID
	}
	return 0
}

func (x *ValuesData) GetCtrID() uint32 {
	if x != nil {
		return x.CtrID
	}
	return 0
}

func (x *ValuesData) GetQerID() uint32 {
	if x != nil {
		return x.QerID
	}
	return 0
}

func (x *ValuesData) GetFarID() uint32 {
	if x != nil {
		return x.FarID
	}
	return 0
}

type UPFeBPFCommandClearArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UPFeBPFCommandClearArg) Reset() {
	*x = UPFeBPFCommandClearArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UPFeBPFCommandClearArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFeBPFCommandClearArg) ProtoMessage() {}

func (x *UPFeBPFCommandClearArg) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFeBPFCommandClearArg.ProtoReflect.Descriptor instead.
func (*UPFeBPFCommandClearArg) Descriptor() ([]byte, []int) {
	return file_protobuf_upf_ebpf_msg_proto_rawDescGZIP(), []int{2}
}

type UPFeBPFArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conf *UPFeBPFArg_Conf `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
}

func (x *UPFeBPFArg) Reset() {
	*x = UPFeBPFArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UPFeBPFArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFeBPFArg) ProtoMessage() {}

func (x *UPFeBPFArg) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFeBPFArg.ProtoReflect.Descriptor instead.
func (*UPFeBPFArg) Descriptor() ([]byte, []int) {
	return file_protobuf_upf_ebpf_msg_proto_rawDescGZIP(), []int{3}
}

func (x *UPFeBPFArg) GetConf() *UPFeBPFArg_Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

type UPFeBPFCommandAddPDRArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priority int64       `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Keys     *KeysData   `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`     /// The values to check for in each field.
	Masks    *KeysData   `protobuf:"bytes,3,opt,name=masks,proto3" json:"masks,omitempty"`   /// The bitmask for each field -- set `0x0` to ignore the field altogether.
	Values   *ValuesData `protobuf:"bytes,4,opt,name=values,proto3" json:"values,omitempty"` /// The values to check for in each fieldv.
}

func (x *UPFeBPFCommandAddPDRArg) Reset() {
	*x = UPFeBPFCommandAddPDRArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UPFeBPFCommandAddPDRArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFeBPFCommandAddPDRArg) ProtoMessage() {}

func (x *UPFeBPFCommandAddPDRArg) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFeBPFCommandAddPDRArg.ProtoReflect.Descriptor instead.
func (*UPFeBPFCommandAddPDRArg) Descriptor() ([]byte, []int) {
	return file_protobuf_upf_ebpf_msg_proto_rawDescGZIP(), []int{4}
}

func (x *UPFeBPFCommandAddPDRArg) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UPFeBPFCommandAddPDRArg) GetKeys() *KeysData {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *UPFeBPFCommandAddPDRArg) GetMasks() *KeysData {
	if x != nil {
		return x.Masks
	}
	return nil
}

func (x *UPFeBPFCommandAddPDRArg) GetValues() *ValuesData {
	if x != nil {
		return x.Values
	}
	return nil
}

type UPFeBPFArg_Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessPort   string `protobuf:"bytes,1,opt,name=access_port,json=accessPort,proto3" json:"access_port,omitempty"` /// Name of the access port
	CorePort     string `protobuf:"bytes,2,opt,name=core_port,json=corePort,proto3" json:"core_port,omitempty"`       /// Name of the core port
	EnablePrintk bool   `protobuf:"varint,3,opt,name=enable_printk,json=enablePrintk,proto3" json:"enable_printk,omitempty"`
}

func (x *UPFeBPFArg_Conf) Reset() {
	*x = UPFeBPFArg_Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UPFeBPFArg_Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFeBPFArg_Conf) ProtoMessage() {}

func (x *UPFeBPFArg_Conf) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_upf_ebpf_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFeBPFArg_Conf.ProtoReflect.Descriptor instead.
func (*UPFeBPFArg_Conf) Descriptor() ([]byte, []int) {
	return file_protobuf_upf_ebpf_msg_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UPFeBPFArg_Conf) GetAccessPort() string {
	if x != nil {
		return x.AccessPort
	}
	return ""
}

func (x *UPFeBPFArg_Conf) GetCorePort() string {
	if x != nil {
		return x.CorePort
	}
	return ""
}

func (x *UPFeBPFArg_Conf) GetEnablePrintk() bool {
	if x != nil {
		return x.EnablePrintk
	}
	return false
}

var File_protobuf_upf_ebpf_msg_proto protoreflect.FileDescriptor

var file_protobuf_upf_ebpf_msg_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x70, 0x66, 0x5f, 0x65,
	0x62, 0x70, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75,
	0x70, 0x66, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x70, 0x62, 0x22, 0x8c, 0x02, 0x0a, 0x08, 0x4b,
	0x65, 0x79, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x49, 0x66,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x72, 0x63, 0x49, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x50, 0x34,
	0x44, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x50, 0x34, 0x44, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x54, 0x45, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x54, 0x45, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x65, 0x49, 0x50, 0x73,
	0x72, 0x63, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x65,
	0x49, 0x50, 0x73, 0x72, 0x63, 0x41, 0x64, 0x64, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x65,
	0x74, 0x49, 0x50, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x69, 0x6e, 0x65, 0x74, 0x49, 0x50, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x65, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x75, 0x65, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x69, 0x6e, 0x65, 0x74, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x69, 0x6e, 0x65, 0x74, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x44, 0x22, 0x7a, 0x0a, 0x0a, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x64, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x64, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x73, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x73,
	0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x74, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x71, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x61, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x66, 0x61, 0x72, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x50, 0x46, 0x65, 0x42, 0x50, 0x46,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x72, 0x67, 0x22,
	0xa9, 0x01, 0x0a, 0x0a, 0x55, 0x50, 0x46, 0x65, 0x42, 0x50, 0x46, 0x41, 0x72, 0x67, 0x12, 0x30,
	0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x75,
	0x70, 0x66, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x50, 0x46, 0x65, 0x42,
	0x50, 0x46, 0x41, 0x72, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66,
	0x1a, 0x69, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x72, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x6b, 0x22, 0xbe, 0x01, 0x0a, 0x17,
	0x55, 0x50, 0x46, 0x65, 0x42, 0x50, 0x46, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x64,
	0x64, 0x50, 0x44, 0x52, 0x41, 0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x75, 0x70, 0x66, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x70, 0x62, 0x2e,
	0x4b, 0x65, 0x79, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x2b,
	0x0a, 0x05, 0x6d, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x75, 0x70, 0x66, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x6d, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x70,
	0x66, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6d, 0x65, 0x63, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x75, 0x70, 0x66, 0x2d, 0x65, 0x70, 0x63, 0x2f,
	0x70, 0x66, 0x63, 0x70, 0x69, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x62, 0x65, 0x73, 0x73, 0x5f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_upf_ebpf_msg_proto_rawDescOnce sync.Once
	file_protobuf_upf_ebpf_msg_proto_rawDescData = file_protobuf_upf_ebpf_msg_proto_rawDesc
)

func file_protobuf_upf_ebpf_msg_proto_rawDescGZIP() []byte {
	file_protobuf_upf_ebpf_msg_proto_rawDescOnce.Do(func() {
		file_protobuf_upf_ebpf_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_upf_ebpf_msg_proto_rawDescData)
	})
	return file_protobuf_upf_ebpf_msg_proto_rawDescData
}

var file_protobuf_upf_ebpf_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_upf_ebpf_msg_proto_goTypes = []interface{}{
	(*KeysData)(nil),                // 0: upf_ebpf.pb.KeysData
	(*ValuesData)(nil),              // 1: upf_ebpf.pb.ValuesData
	(*UPFeBPFCommandClearArg)(nil),  // 2: upf_ebpf.pb.UPFeBPFCommandClearArg
	(*UPFeBPFArg)(nil),              // 3: upf_ebpf.pb.UPFeBPFArg
	(*UPFeBPFCommandAddPDRArg)(nil), // 4: upf_ebpf.pb.UPFeBPFCommandAddPDRArg
	(*UPFeBPFArg_Conf)(nil),         // 5: upf_ebpf.pb.UPFeBPFArg.Conf
}
var file_protobuf_upf_ebpf_msg_proto_depIdxs = []int32{
	5, // 0: upf_ebpf.pb.UPFeBPFArg.conf:type_name -> upf_ebpf.pb.UPFeBPFArg.Conf
	0, // 1: upf_ebpf.pb.UPFeBPFCommandAddPDRArg.keys:type_name -> upf_ebpf.pb.KeysData
	0, // 2: upf_ebpf.pb.UPFeBPFCommandAddPDRArg.masks:type_name -> upf_ebpf.pb.KeysData
	1, // 3: upf_ebpf.pb.UPFeBPFCommandAddPDRArg.values:type_name -> upf_ebpf.pb.ValuesData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_upf_ebpf_msg_proto_init() }
func file_protobuf_upf_ebpf_msg_proto_init() {
	if File_protobuf_upf_ebpf_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_upf_ebpf_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeysData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_upf_ebpf_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValuesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_upf_ebpf_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UPFeBPFCommandClearArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_upf_ebpf_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UPFeBPFArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_upf_ebpf_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UPFeBPFCommandAddPDRArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_upf_ebpf_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UPFeBPFArg_Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_upf_ebpf_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_upf_ebpf_msg_proto_goTypes,
		DependencyIndexes: file_protobuf_upf_ebpf_msg_proto_depIdxs,
		MessageInfos:      file_protobuf_upf_ebpf_msg_proto_msgTypes,
	}.Build()
	File_protobuf_upf_ebpf_msg_proto = out.File
	file_protobuf_upf_ebpf_msg_proto_rawDesc = nil
	file_protobuf_upf_ebpf_msg_proto_goTypes = nil
	file_protobuf_upf_ebpf_msg_proto_depIdxs = nil
}
